# GitLab CI Template for Multi-Language AI Code Review
# Features: 2-pass verification with automatic linter integration for all languages
# This template auto-detects the language and runs appropriate reviews

ai_code_review:
  stage: code-review
  image: python:3.11
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
  before_script:
    # Install common linters for multi-language support
    - apt-get update -qq && apt-get install -y curl
    - pip install pylint  # Python linter
    # Note: Add language-specific linters based on your project
    # - npm install -g eslint  # JavaScript/TypeScript (requires Node)
    # - Install Go and golangci-lint if needed
    - git clone https://github.com/myusufkuncie/ai-reviewer.git /tmp/ai-reviewer
    - cd /tmp/ai-reviewer
    - pip install -r requirements.txt --break-system-packages
  script:
    - cp "$CI_PROJECT_DIR/.ai-review-config.json" /tmp/ai-reviewer/
    - cd /tmp/ai-reviewer
    - echo "Running AI Code Review for MR !${CI_MERGE_REQUEST_IID}"
    - python main_gitlab.py
  after_script:
    - |
      if [ -f .review_summary.json ]; then
        echo "Review Summary:"
        cat .review_summary.json
      fi
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    OPENROUTER_API_KEY: $OPENROUTER_API_KEY
    REVIEW_LANGUAGE: 'auto'
    AI_REVIEWER_DEBUG: 'false'
  cache:
    key: ai-review-cache-${CI_COMMIT_REF_SLUG}
    paths:
      - .review_cache/
    policy: pull-push
  artifacts:
    when: always
    paths:
      - .review_cache/
      - .review_summary.json
    reports:
      dotenv: .review_summary.env
    expire_in: 7 days
  allow_failure: true
  timeout: 10m
  tags:
    - docker

# Optional: Run review only on specific file changes
ai_code_review_conditional:
  extends: ai_code_review
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.py"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.tsx"
      - "**/*.dart"
      - "**/*.go"
      - "**/*.java"
      - "requirements.txt"
      - "package.json"
      - "pubspec.yaml"
      - "go.mod"
