# GitLab CI Template for PHP/Laravel AI Code Review
# Features: 2-pass verification with automatic phpcs integration

ai-review-php:
  stage: test
  image: php:8.2
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  before_script:
    # Install Composer and phpcs
    - apt-get update -qq && apt-get install -y python3 python3-pip git curl unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer global require "squizlabs/php_codesniffer=*"
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - phpcs --version
    # Install AI Reviewer
    - git clone https://github.com/myusufkuncie/ai-reviewer.git /tmp/ai-reviewer
    - cd /tmp/ai-reviewer
    - pip3 install -r requirements.txt
  script:
    - cd /tmp/ai-reviewer
    - python3 main_gitlab.py
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    OPENROUTER_API_KEY: $OPENROUTER_API_KEY
    REVIEW_LANGUAGE: 'php'
    REVIEW_FRAMEWORK: 'laravel'
  cache:
    key: ai-review-cache-php-${CI_COMMIT_REF_SLUG}
    paths:
      - .review_cache/
      - vendor/
  artifacts:
    when: always
    paths:
      - .review_cache/
    expire_in: 7 days
  allow_failure: true
  retry:
    max: 2
    when:
      - api_failure
      - runner_system_failure
