# GitLab CI Template for Python/Django AI Code Review
# Features: 2-pass verification with automatic pylint integration
# Include this in your main .gitlab-ci.yml:
# include:
#   - local: '.gitlab-ci-ai-review.yml'

ai_code_review:
  stage: code-review
  image: python:3.11
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  before_script:
    - pip install pylint  # Install linter for 2-pass verification
    - git clone https://github.com/myusufkuncie/ai-reviewer.git /tmp/ai-reviewer
    - cd /tmp/ai-reviewer
    - pip install -r requirements.txt
  script:
    - cp "$CI_PROJECT_DIR/.ai-review-config.json" /tmp/ai-reviewer/
    - cd /tmp/ai-reviewer
    - python main_gitlab.py
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    OPENROUTER_API_KEY: $OPENROUTER_API_KEY
    REVIEW_LANGUAGE: 'python'
    REVIEW_FRAMEWORK: 'django'
  cache:
    key: ai-review-cache-python-${CI_COMMIT_REF_SLUG}
    paths:
      - .review_cache/
  artifacts:
    when: always
    paths:
      - .review_cache/
    expire_in: 7 days
  allow_failure: true
